/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import java.net.URI

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.70"
    id("application")
}


repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    maven {
        url = URI("https://repo.eclipse.org/content/repositories/egit-releases/")
    }
}

dependencies {
    val vertxVersion = "4.0.0-milestone4"
    val jacksonVersion = "2.10.3"
    val teamCityRestClientVersion = "1.7.27"
    val guiceVersion = "4.2.3"
    implementation("io.vertx:vertx-web-client:$vertxVersion")
    implementation("io.vertx:vertx-core:$vertxVersion")
    implementation("io.vertx:vertx-web:$vertxVersion")
    implementation("io.vertx:vertx-lang-kotlin:$vertxVersion")

    implementation("com.google.inject:guice:$guiceVersion")
    implementation("javax.inject:javax.inject:1")

    implementation("com.fasterxml.jackson.core:jackson-core:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:$jacksonVersion")

    implementation("org.eclipse.mylyn.github:org.eclipse.mylyn.github.core:5.7.0.202003110725-r")
    implementation("org.jetbrains.teamcity:teamcity-rest-client:$teamCityRestClientVersion")
    implementation("com.jcabi:jcabi-github:0.41")


    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}

tasks.named("run", JavaExec::class.java) {
    args = listOf("run", "org.gradle.bot.MainVerticle",
            "--launcher-class=org.gradle.bot.MainVerticle")
    main = "io.vertx.core.Launcher"
}

