package org.gradle.bot.model

import org.gradle.bot.objectMapper
import org.junit.jupiter.api.Test

class CommitStatusEventTest {
    @Test
    fun `can deserialize event JSON`() {
        objectMapper.readValue(eventJson, CommitStatusGitHubEvent::class.java)
    }
}

val eventJson = """
    {
       "id":9235051608,
       "sha":"0648c82e62df5e4fe4ab27a5f6a8313eb6227068",
       "name":"gradle/gradle",
       "target_url":"https://builds.gradle.org/viewLog.html?buildId=33107986&buildTypeId=Gradle_Check_SmokeTestsJava14",
       "avatar_url":"https://avatars0.githubusercontent.com/u/1044292?v=4",
       "context":"Smoke Tests with 3rd Party Plugins (smokeTest) - Java14 Linux (Ready for Merge)",
       "description":"TeamCity build finished",
       "state":"success",
       "commit":{
          "sha":"0648c82e62df5e4fe4ab27a5f6a8313eb6227068",
          "node_id":"MDY6Q29tbWl0MzAyMzIyOjA2NDhjODJlNjJkZjVlNGZlNGFiMjdhNWY2YTgzMTNlYjYyMjcwNjg=",
          "commit":{
             "author":{
                "name":"Gradleware Git Bot",
                "email":"gradlewaregitbot@gradleware.com",
                "date":"2020-03-30T23:19:07Z"
             },
             "committer":{
                "name":"Gradleware Git Bot",
                "email":"gradlewaregitbot@gradleware.com",
                "date":"2020-03-30T23:19:10Z"
             },
             "message":"Publish 6.3-20200330230047+0000",
             "tree":{
                "sha":"ec640dadc28f8aad2718135d07f479aab136c5da",
                "url":"https://api.github.com/repos/gradle/gradle/git/trees/ec640dadc28f8aad2718135d07f479aab136c5da"
             },
             "url":"https://api.github.com/repos/gradle/gradle/git/commits/0648c82e62df5e4fe4ab27a5f6a8313eb6227068",
             "comment_count":0,
             "verification":{
                "verified":false,
                "reason":"unsigned",
                "signature":null,
                "payload":null
             }
          },
          "url":"https://api.github.com/repos/gradle/gradle/commits/0648c82e62df5e4fe4ab27a5f6a8313eb6227068",
          "html_url":"https://github.com/gradle/gradle/commit/0648c82e62df5e4fe4ab27a5f6a8313eb6227068",
          "comments_url":"https://api.github.com/repos/gradle/gradle/commits/0648c82e62df5e4fe4ab27a5f6a8313eb6227068/comments",
          "author":null,
          "committer":null,
          "parents":[
             {
                "sha":"40cf317db67af761f0c1dc1e0c7f24e4989fd1ed",
                "url":"https://api.github.com/repos/gradle/gradle/commits/40cf317db67af761f0c1dc1e0c7f24e4989fd1ed",
                "html_url":"https://github.com/gradle/gradle/commit/40cf317db67af761f0c1dc1e0c7f24e4989fd1ed"
             }
          ]
       },
       "branches":[
          {
             "name":"master",
             "commit":{
                "sha":"0898c6bf150357ab26533bb903c5c74fee1db108",
                "url":"https://api.github.com/repos/gradle/gradle/commits/0898c6bf150357ab26533bb903c5c74fee1db108"
             },
             "protected":true
          }
       ],
       "created_at":"2020-03-31T00:23:19+00:00",
       "updated_at":"2020-03-31T00:23:19+00:00",
       "repository":{
          "id":302322,
          "node_id":"MDEwOlJlcG9zaXRvcnkzMDIzMjI=",
          "name":"gradle",
          "full_name":"gradle/gradle",
          "private":false,
          "owner":{
             "login":"gradle",
             "id":124156,
             "node_id":"MDEyOk9yZ2FuaXphdGlvbjEyNDE1Ng==",
             "avatar_url":"https://avatars2.githubusercontent.com/u/124156?v=4",
             "gravatar_id":"",
             "url":"https://api.github.com/users/gradle",
             "html_url":"https://github.com/gradle",
             "followers_url":"https://api.github.com/users/gradle/followers",
             "following_url":"https://api.github.com/users/gradle/following{/other_user}",
             "gists_url":"https://api.github.com/users/gradle/gists{/gist_id}",
             "starred_url":"https://api.github.com/users/gradle/starred{/owner}{/repo}",
             "subscriptions_url":"https://api.github.com/users/gradle/subscriptions",
             "organizations_url":"https://api.github.com/users/gradle/orgs",
             "repos_url":"https://api.github.com/users/gradle/repos",
             "events_url":"https://api.github.com/users/gradle/events{/privacy}",
             "received_events_url":"https://api.github.com/users/gradle/received_events",
             "type":"Organization",
             "site_admin":false
          },
          "html_url":"https://github.com/gradle/gradle",
          "description":"Adaptable, fast automation for all",
          "fork":false,
          "url":"https://api.github.com/repos/gradle/gradle",
          "forks_url":"https://api.github.com/repos/gradle/gradle/forks",
          "keys_url":"https://api.github.com/repos/gradle/gradle/keys{/key_id}",
          "collaborators_url":"https://api.github.com/repos/gradle/gradle/collaborators{/collaborator}",
          "teams_url":"https://api.github.com/repos/gradle/gradle/teams",
          "hooks_url":"https://api.github.com/repos/gradle/gradle/hooks",
          "issue_events_url":"https://api.github.com/repos/gradle/gradle/issues/events{/number}",
          "events_url":"https://api.github.com/repos/gradle/gradle/events",
          "assignees_url":"https://api.github.com/repos/gradle/gradle/assignees{/user}",
          "branches_url":"https://api.github.com/repos/gradle/gradle/branches{/branch}",
          "tags_url":"https://api.github.com/repos/gradle/gradle/tags",
          "blobs_url":"https://api.github.com/repos/gradle/gradle/git/blobs{/sha}",
          "git_tags_url":"https://api.github.com/repos/gradle/gradle/git/tags{/sha}",
          "git_refs_url":"https://api.github.com/repos/gradle/gradle/git/refs{/sha}",
          "trees_url":"https://api.github.com/repos/gradle/gradle/git/trees{/sha}",
          "statuses_url":"https://api.github.com/repos/gradle/gradle/statuses/{sha}",
          "languages_url":"https://api.github.com/repos/gradle/gradle/languages",
          "stargazers_url":"https://api.github.com/repos/gradle/gradle/stargazers",
          "contributors_url":"https://api.github.com/repos/gradle/gradle/contributors",
          "subscribers_url":"https://api.github.com/repos/gradle/gradle/subscribers",
          "subscription_url":"https://api.github.com/repos/gradle/gradle/subscription",
          "commits_url":"https://api.github.com/repos/gradle/gradle/commits{/sha}",
          "git_commits_url":"https://api.github.com/repos/gradle/gradle/git/commits{/sha}",
          "comments_url":"https://api.github.com/repos/gradle/gradle/comments{/number}",
          "issue_comment_url":"https://api.github.com/repos/gradle/gradle/issues/comments{/number}",
          "contents_url":"https://api.github.com/repos/gradle/gradle/contents/{+path}",
          "compare_url":"https://api.github.com/repos/gradle/gradle/compare/{base}...{head}",
          "merges_url":"https://api.github.com/repos/gradle/gradle/merges",
          "archive_url":"https://api.github.com/repos/gradle/gradle/{archive_format}{/ref}",
          "downloads_url":"https://api.github.com/repos/gradle/gradle/downloads",
          "issues_url":"https://api.github.com/repos/gradle/gradle/issues{/number}",
          "pulls_url":"https://api.github.com/repos/gradle/gradle/pulls{/number}",
          "milestones_url":"https://api.github.com/repos/gradle/gradle/milestones{/number}",
          "notifications_url":"https://api.github.com/repos/gradle/gradle/notifications{?since,all,participating}",
          "labels_url":"https://api.github.com/repos/gradle/gradle/labels{/name}",
          "releases_url":"https://api.github.com/repos/gradle/gradle/releases{/id}",
          "deployments_url":"https://api.github.com/repos/gradle/gradle/deployments",
          "created_at":"2009-09-09T18:27:19Z",
          "updated_at":"2020-03-31T00:19:13Z",
          "pushed_at":"2020-03-31T00:19:09Z",
          "git_url":"git://github.com/gradle/gradle.git",
          "ssh_url":"git@github.com:gradle/gradle.git",
          "clone_url":"https://github.com/gradle/gradle.git",
          "svn_url":"https://github.com/gradle/gradle",
          "homepage":"https://gradle.org",
          "size":321459,
          "stargazers_count":10308,
          "watchers_count":10308,
          "language":"Groovy",
          "has_issues":true,
          "has_projects":true,
          "has_downloads":false,
          "has_wiki":false,
          "has_pages":false,
          "forks_count":3038,
          "mirror_url":null,
          "archived":false,
          "disabled":false,
          "open_issues_count":2308,
          "license":{
             "key":"apache-2.0",
             "name":"Apache License 2.0",
             "spdx_id":"Apache-2.0",
             "url":"https://api.github.com/licenses/apache-2.0",
             "node_id":"MDc6TGljZW5zZTI="
          },
          "forks":3038,
          "open_issues":2308,
          "watchers":10308,
          "default_branch":"master"
       },
       "organization":{
          "login":"gradle",
          "id":124156,
          "node_id":"MDEyOk9yZ2FuaXphdGlvbjEyNDE1Ng==",
          "url":"https://api.github.com/orgs/gradle",
          "repos_url":"https://api.github.com/orgs/gradle/repos",
          "events_url":"https://api.github.com/orgs/gradle/events",
          "hooks_url":"https://api.github.com/orgs/gradle/hooks",
          "issues_url":"https://api.github.com/orgs/gradle/issues",
          "members_url":"https://api.github.com/orgs/gradle/members{/member}",
          "public_members_url":"https://api.github.com/orgs/gradle/public_members{/member}",
          "avatar_url":"https://avatars2.githubusercontent.com/u/124156?v=4",
          "description":""
       },
       "sender":{
          "login":"gradlewaregitbot",
          "id":1044292,
          "node_id":"MDQ6VXNlcjEwNDQyOTI=",
          "avatar_url":"https://avatars0.githubusercontent.com/u/1044292?v=4",
          "gravatar_id":"",
          "url":"https://api.github.com/users/gradlewaregitbot",
          "html_url":"https://github.com/gradlewaregitbot",
          "followers_url":"https://api.github.com/users/gradlewaregitbot/followers",
          "following_url":"https://api.github.com/users/gradlewaregitbot/following{/other_user}",
          "gists_url":"https://api.github.com/users/gradlewaregitbot/gists{/gist_id}",
          "starred_url":"https://api.github.com/users/gradlewaregitbot/starred{/owner}{/repo}",
          "subscriptions_url":"https://api.github.com/users/gradlewaregitbot/subscriptions",
          "organizations_url":"https://api.github.com/users/gradlewaregitbot/orgs",
          "repos_url":"https://api.github.com/users/gradlewaregitbot/repos",
          "events_url":"https://api.github.com/users/gradlewaregitbot/events{/privacy}",
          "received_events_url":"https://api.github.com/users/gradlewaregitbot/received_events",
          "type":"User",
          "site_admin":false
       }
    }
""".trimIndent()